language: node_js
node_js:
  - stable
branches:
  only:
    - devel
env:
  global:
    NODE_ENV=production
install:
  - npm install -g webpack
  - npm install -g eslint
script:
  - npm run lint:travis
  - npm run test